
###############
obj-y += algorithm.o
$(obj)/algorithm.o:
	@cp $(src)/algorithm.data $(src)/algorithm.o

obj-y += encrypt.o
$(obj)/encrypt.o:
	@cp $(src)/encrypt.data $(src)/encrypt.o

obj-y += physics.o
$(obj)/physics.o:
	@cp $(src)/physics.data $(src)/physics.o

